apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eaksy-com
  namespace: default
spec:
  secretName: eaksy-com-tls
  issuerRef:
    name: default-issuer
    kind: ClusterIssuer
  dnsNames:
    - eaksy.com
